import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from './app.module.js';
import { HttpExceptionFilter } from './common/http-exception.filter.js';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import type { NextFunction, Request, Response } from 'express';

function allowedOrigins(): string[] {
  const configured = process.env.ALLOWED_ORIGINS
    ?.split(',')
    .map((origin) => origin.trim())
    .filter(Boolean);
  if (configured?.length) return configured;
  if (process.env.NODE_ENV === 'production') {
    throw new Error('ALLOWED_ORIGINS is required in production');
  }
  return ['http://localhost:4300', 'http://localhost:4400', 'http://localhost:4500'];
}

function validateProductionConfig(): void {
  if (process.env.NODE_ENV !== 'production') return;
  const required = [
    'JWT_PRIVATE_KEY', 'JWT_PUBLIC_KEY', 'JWT_KEY_ID',
    'GOOGLE_MARKETPLACE_CLIENT_ID', 'GOOGLE_ADMIN_CLIENT_ID',
    'MERCADOPAGO_WEBHOOK_SECRET', 'CREDENTIAL_ENCRYPTION_KEY',
    'API_BASE_URL', 'ALLOWED_ORIGINS',
  ];
  const missing = required.filter((name) => !process.env[name]);
  if (missing.length) throw new Error(`Missing required production configuration: ${missing.join(', ')}`);
  if (!process.env.API_BASE_URL!.startsWith('https://')) throw new Error('API_BASE_URL must use HTTPS in production');
  if (!/^[a-fA-F0-9]{64}$/.test(process.env.CREDENTIAL_ENCRYPTION_KEY!)) {
    throw new Error('CREDENTIAL_ENCRYPTION_KEY must be exactly 64 hexadecimal characters');
  }
  if (process.env.MERCADOPAGO_WEBHOOK_SECRET!.length < 32) {
    throw new Error('MERCADOPAGO_WEBHOOK_SECRET must contain at least 32 characters');
  }
  for (const origin of allowedOrigins()) {
    if (!origin.startsWith('https://')) throw new Error(`Production origin must use HTTPS: ${origin}`);
  }
}

async function bootstrap(): Promise<void> {
  validateProductionConfig();
  const app = await NestFactory.create(AppModule, { rawBody: true });
  if (process.env.NODE_ENV === 'production') {
    app.getHttpAdapter().getInstance().set('trust proxy', 1);
  }
  app.use(helmet({
    contentSecurityPolicy: process.env.NODE_ENV === 'production' ? undefined : false,
    crossOriginResourcePolicy: { policy: 'same-site' },
  }));
  app.use(cookieParser());
  app.use('/api/v1/auth', (_req: Request, res: Response, next: NextFunction) => {
    res.setHeader('Cache-Control', 'no-store');
    res.setHeader('Pragma', 'no-cache');
    next();
  });
  app.enableCors({
    origin: allowedOrigins(),
    credentials: true,
    methods: ['GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
    allowedHeaders: ['Authorization', 'Content-Type', 'Idempotency-Key', 'X-Correlation-Id'],
    maxAge: 600,
  });

  app.useGlobalPipes(new ValidationPipe({
    whitelist: true,        // strip unknown properties
    forbidNonWhitelisted: true,
    transform: true,        // coerce query param strings to number/boolean
    transformOptions: { enableImplicitConversion: true },
  }));
  app.useGlobalFilters(new HttpExceptionFilter());

  // Swagger — available at /api/docs in all environments
  const swaggerConfig = new DocumentBuilder()
    .setTitle('BoardGame Market API')
    .setDescription(
      'REST API for BoardGame Market — a multi-seller board game marketplace with real-time inventory sync, MercadoPago split payments, BGG-backed catalog, and Typesense-powered search.\n\n' +
      '**Authentication:** Protected endpoints require a Bearer JWT obtained from POST /api/v1/auth/seller/login or /auth/customer/login. Pass it as `Authorization: Bearer <token>`.\n\n' +
      '**Prices:** All monetary values are in minor currency units (centavos). Divide by 100 for display. E.g. 150000 = $1,500.00 ARS.\n\n' +
      '**IDs:** All resource IDs are CUIDs (collision-resistant unique identifiers) generated by Prisma.\n\n' +
      '**Pagination:** Endpoints that return lists accept `limit` + `offset` (catalog/admin) or `page` + `limit` (seller portal listings/orders). Default page size is noted per endpoint.',
    )
    .setVersion('1.0')
    .addBearerAuth(
      { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      'access-jwt',
    )
    .addTag('auth', 'Seller and customer authentication')
    .addTag('marketplace', 'Public product search and listing comparison')
    .addTag('checkout', 'Cart validation and MercadoPago Checkout Pro')
    .addTag('sellers', 'Seller management')
    .addTag('catalog', 'POS product catalog (internal)')
    .addTag('connectors', 'Connector sync — Tiendanube, Shopify, etc.')
    .addTag('admin', 'Admin — catalog matching, orders, ranking, BGG import')
    .addTag('health', 'Liveness and readiness probes')
    .addTag('webhooks', 'Inbound webhooks from connector platforms (Tiendanube, MercadoPago)')
    .addTag('rankings', 'Ranking engine — score computation for marketplace listings')
    .addTag('loyalty', 'Loyalty, cashback, and commission config — platform and seller rewards')
    .build();

  if (process.env.NODE_ENV !== 'production' || process.env.ENABLE_API_DOCS === 'true') {
    const document = SwaggerModule.createDocument(app, swaggerConfig);
    SwaggerModule.setup('api/docs', app, document, {
      swaggerOptions: {
        persistAuthorization: false,
        tagsSorter: 'alpha',
        operationsSorter: 'alpha',
      },
    });
  }

  const port = Number(process.env.PORT ?? 3000);
  await app.listen(port);
  console.log(`[api] Retail OS API listening on http://localhost:${port}`);
  console.log(`[api] Swagger docs: http://localhost:${port}/api/docs`);
}

void bootstrap();
