import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from './app.module.js';
import { HttpExceptionFilter } from './common/http-exception.filter.js';

async function bootstrap(): Promise<void> {
  const app = await NestFactory.create(AppModule);
  app.enableCors();

  app.useGlobalPipes(new ValidationPipe({
    whitelist: true,        // strip unknown properties
    forbidNonWhitelisted: true,
    transform: true,        // coerce query param strings to number/boolean
    transformOptions: { enableImplicitConversion: true },
  }));
  app.useGlobalFilters(new HttpExceptionFilter());

  // Swagger — available at /api/docs in all environments
  const swaggerConfig = new DocumentBuilder()
    .setTitle('BoardGame Market API')
    .setDescription(
      'REST API for BoardGame Market — a multi-seller board game marketplace with real-time inventory sync, MercadoPago split payments, BGG-backed catalog, and Typesense-powered search.\n\n' +
      '**Authentication:** Protected endpoints require a Bearer JWT obtained from POST /api/v1/auth/seller/login or /auth/customer/login. Pass it as `Authorization: Bearer <token>`.\n\n' +
      '**Prices:** All monetary values are in minor currency units (centavos). Divide by 100 for display. E.g. 150000 = $1,500.00 ARS.\n\n' +
      '**IDs:** All resource IDs are CUIDs (collision-resistant unique identifiers) generated by Prisma.\n\n' +
      '**Pagination:** Endpoints that return lists accept `limit` + `offset` (catalog/admin) or `page` + `limit` (seller portal listings/orders). Default page size is noted per endpoint.',
    )
    .setVersion('1.0')
    .addBearerAuth(
      { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      'seller-jwt',
    )
    .addTag('auth', 'Seller and customer authentication')
    .addTag('marketplace', 'Public product search and listing comparison')
    .addTag('checkout', 'Cart validation and MercadoPago Checkout Pro')
    .addTag('sellers', 'Seller management')
    .addTag('catalog', 'POS product catalog (internal)')
    .addTag('connectors', 'Connector sync — Tiendanube, Shopify, etc.')
    .addTag('admin', 'Admin — catalog matching, orders, ranking, BGG import')
    .addTag('health', 'Liveness and readiness probes')
    .addTag('webhooks', 'Inbound webhooks from connector platforms (Tiendanube, MercadoPago)')
    .addTag('rankings', 'Ranking engine — score computation for marketplace listings')
    .build();

  const document = SwaggerModule.createDocument(app, swaggerConfig);
  SwaggerModule.setup('api/docs', app, document, {
    swaggerOptions: {
      persistAuthorization: true,
      tagsSorter: 'alpha',
      operationsSorter: 'alpha',
    },
  });

  const port = Number(process.env.PORT ?? 3000);
  await app.listen(port);
  console.log(`[api] Retail OS API listening on http://localhost:${port}`);
  console.log(`[api] Swagger docs: http://localhost:${port}/api/docs`);
}

void bootstrap();
