worker_processes auto;

events {
  worker_connections 1024;
}

http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  map $server_port $odoo_menu_id {
    8070 111; # Inventory
    8071 576; # Sales
    8073 373; # CRM
    8074 526; # Purchase
    8075 318; # Invoicing
    8076 504; # Manufacturing
    8077 550; # Point of Sale
    8078 441; # Project
    8079 247; # Employees
    8080 463; # Website
    8081 171; # Contacts
    8082 163; # Calendar
    8083 229; # Maintenance
    8084 626; # Repairs
    8085 491; # Expenses
    8086 398; # Recruitment
    8087 286; # Attendances
    8088 295; # Time Off
    8089 184; # Fleet
    8090 422; # Email Marketing
    8091 275; # Events
    8092 268; # Surveys
    8093 212; # Lunch
    8094 459; # Dashboards
    8095 74;  # Discuss
    8096 525; # To-do
    8097 158; # Link Tracker
  }

  upstream odoo_http {
    server odoo:8069;
  }

  upstream odoo_realtime {
    server odoo:8072;
  }

  server {
    listen 8070;
    listen 8071;
    listen 8073;
    listen 8074;
    listen 8075;
    listen 8076;
    listen 8077;
    listen 8078;
    listen 8079;
    listen 8080;
    listen 8081;
    listen 8082;
    listen 8083;
    listen 8084;
    listen 8085;
    listen 8086;
    listen 8087;
    listen 8088;
    listen 8089;
    listen 8090;
    listen 8091;
    listen 8092;
    listen 8093;
    listen 8094;
    listen 8095;
    listen 8096;
    listen 8097;

    server_name _;
    client_max_body_size 100m;
    proxy_read_timeout 720s;
    proxy_connect_timeout 30s;
    proxy_send_timeout 720s;

    location = / {
      return 302 "/web#menu_id=$odoo_menu_id";
    }

    location /websocket {
      proxy_pass http://odoo_realtime;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
      proxy_pass http://odoo_http;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
    }
  }
}
